### ISSUE TITLE
Clarify transparency/discoverability on main README

### ISSUE THREAD

**Issue by mhutchinson** [google/model-transparency#27]
The repo name and main title of the README introduces this work as transparency, but the body of the text talks primarily about integrity achieved via signatures:

```
This project demonstrates how to protect the integrity of a model by signing it with [Sigstore](https://www.sigstore.dev/), a tool for making code signatures transparent without requiring key maintenance. When users download a given version of a signed model they can check that the signature comes from a known or trusted identity and thus that the model hasn't been tampered with after training.
```

The implicit claim above is that transparency is achieved by virtue of logging it to SigStore. Logging such claims is necessary for transparency but not sufficient. The missing part of the transparency puzzle is that identity owners will tail the log seeking to discover any signatures issued from their identity that they are not aware of. This completes the signature transparency story, as key compromise will be detected, and thus authenticity can be relied upon.

@haydentherapper has more context on this as we discussed this yesterday.

**Comment by haydentherapper** [comment]
Thanks Martin for mentioning this. I think this was implicit to us, but would not be to a newcomer in this space. https://github.com/sigstore/rekor-monitor is a work in progress, but the identity monitoring portion is in a far better state now. I'd recommend we update the readme to go a bit more in depth into the claims that are added to the log and how to monitor for those claims.
