### ISSUE TITLE
SLSA for ML models examples fails for runners other than mac

### ISSUE THREAD

**Issue by Sita04** [google/model-transparency#79]
I tried running the "SLSA for ML models" GA and it fails for runners other than `macOS`.

In [this](https://github.com/google/model-transparency/blob/main/.github/workflows/slsa_for_ml.yml#L35) line from `slsa_for_ml.yaml`, the requirements file is tuned to the specific os runner, but the corresponding yaml file is not found in the folder specified.

**Comment by mihaimaruseac** [comment]
Apologies for this, we accidentally broke it while trying to have requirements files specific for each OS.

I'll try to fix today.

**Comment by mihaimaruseac** [comment]
The workflow [now works](https://github.com/google/model-transparency/actions/runs/7425449512/job/20207114370) but only for Linux. Will do a few more changes to make it run on other operating systems too.

**Comment by mihaimaruseac** [comment]
The training now works on all 3 operating systems, but it seems we have an issue on generating the SLSA provenance. Will revisit later

**Comment by mihaimaruseac** [comment]
Sorry for the delay. This should now work
